blank_issues_enabled: true
contact_links:
  - name: Shopify Partners Community ğŸ™Œ
    url: https://www.shopify.com/partners/community#conversation
    about: Connect with Shopify and other Shopify Partners through our online communities!
  - name: Shopify CLI 2.0 issues ğŸ“
    url: https://www.github.com/Shopify/shopify-cli/issues/new/choose
    about: |-
      This is where you can create issues for Shopify CLI 3.0.
      
      Are you using our previous CLI? Please create an issue there instead.
