# This file stores configurations for your Shopify app UI extension.

name = "{{name}}"
type = "{{uiExtensionType}}"

# [[metafield]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafield]]
# namespace = "my-namespace"
# key = "my-key-2"
