on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: ["packages/*/src/**"]
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: mskelton/changelog-reminder-action@v2
        with:
          changelogRegex: \.changeset
          message: |
            We detected some changes at packages/*/src and there are no updates in the .changeset.
            If the changes are user-facing, run "yarn changeset add" to track your changes and include them in the next release CHANGELOG.
