name: Reviewers reminder

on:
  pull_request:
    types:
      - opened

jobs:
  remind:
    name: "[PR] Remind reviewers"
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@ffe8f97ccc63ce12c3c23c6885b169db67958d3b # pin@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            Thanks for your contribution!

            Depending on what you are working on, you may want to request a review from a Shopify team:
            - Themes: @shopify/advanced-edits
            - UI extensions: @shopify/ui-extensions-cli
              - Checkout UI extensions: @shopify/checkout-ui-extensions-api-stewardship
            - Hydrogen: @shopify/hydrogen
            - Other: @shopify/app-management
